// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://syyjhkqktluhvaknnhfq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN5eWpoa3FrdGx1aHZha25uaGZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5MzUwMDQsImV4cCI6MjA3MzUxMTAwNH0.yexXV_VcR9FvNcKa74KnY5ftjgcOMB4beIvfv2-o8U4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});